### ISSUE TITLE
Escape swift keywords in generated code.

### ISSUE THREAD

**Issue by sdevos** [tomlokhorst/swift-json-gen#34] opened 2016-03-31 12:09 UTC
json-gen produces invalid code if you try to generate decoders for objects with Swift keywords as member names. In swift you can escape keywords with `back ticks`, json-gen should do the same.

e.g.

``` swift
struct Foo {
  let `break`: Bool
}
```

**Comment by tomlokhorst** [comment] 2016-03-31 12:14
Duplicate of https://github.com/tomlokhorst/swift-json-gen/issues/33

**Closed as completed by tomlokhorst** 2016-03-31 12:14 UTC
Labels: duplicate
